export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES'
export const RECEIVE_ATTRACTIONS = 'RECEIVE_ATTRACTIONS'
export const FAVORITE_ATTRACTION = 'FAVORITE_ATTRACTION'
export const UNDO_FAVORITE_ATTRACTION = 'UNDO_FAVORITE_ATTRACTION'
